name: Github Actions Workflows

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  IMAGE_NAME: "ghcr.io/${{ github.repository }}"
  IMAGE_TAG: "${{ github.event.release.tag_name }}"
  REDIS_OM_URL: ${{ secrets.REDIS_OM_URL }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Lowercase Repository Name
      run: |
        IMAGE_NAME_LOWER=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
        echo "IMAGE_NAME=${IMAGE_NAME_LOWER}" >> $GITHUB_ENV

    - name: Determine Image Tag
      run: |
        if [ "release" = "release" ]; then
          echo "IMAGE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
        else
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
        fi

    - name: Debug Environment Variables
      run: |
        echo "IMAGE_NAME: $IMAGE_NAME"
        echo "IMAGE_TAG: $IMAGE_TAG"

    - name: Set up Docker Buildx 
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image 
      uses: docker/build-push-action@v6
      with: 
        context: . 
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          ${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha 
        cache-to: type=gha,mode=max
        build-args: |
          REDIS_OM_URL=${{ secrets.REDIS_OM_URL }}
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}